### ISSUE TITLE
cannot find '_base' module

### ISSUE THREAD

**Issue by mhubel** [JamesRamm/archook#1]
Hello,

I've been trying to use your code to include ArcPy with the Anaconda application. Unfortunately, it fails to import the module '_base' from the geoprocessing folder: 

https://cloud.githubusercontent.com/assets/12075378/10463558/46dfb9dc-71b3-11e5-82d8-d9c274f23671.png

But I can easily locate this module in my windows browser, and it is within the arcpy\geoprocessing folder. Any suggestions for troubleshooting?

**Comment by JamesRamm** [comment]
Is this on simply doing `import arcpy` or something else?

This is not one I have come across. It usually comes down to something not being on the system path.
The underscore often indicates that the module is a wrapper around a dll (or is a `pyd` itself)...

Try adding the folder to your system path manually...archook adds the following folders from the arcgis install dir to the path:

`/arcpy`, `/bin` or `/bin64`, `ArcToolbox/Scripts`.

It may be that something else needs adding...

**Comment by JamesRamm** [comment]
Closing as no response

**Comment by JamesRamm** [comment]
Assuming this is not a problem as there was no response

**Comment by jsta** [comment]
I am getting the same error as OP. I had been trying to point to `arcpy` at `C:\Python27\ArcGIS10.3\python.exe`. Maybe that's a clue?

**Comment by mhw-at-yg** [comment]
I've replicated the issue so re-opening. No details at present because I haven't yet dug into what's different/significant.

**Comment by Hazedd** [comment]
Status?

**Comment by maphew** [comment]
Thanks for the bump. I can't replicate the problem today and my notes don't have the detail to let me reconstruct what I was doing the last time. Do you have a reproducible recipe @Hazedd?

**Comment by Hazedd** [comment]
@maphew Good and a bad thing that i have... I guess. Will dive in to it tonorrow

**Comment by Hazedd** [comment]
@maphew , bit of bummer but arcgis python is just a mess on my pc atm. not sure what happend.... for now i cant reproduce it.

**Comment by mhw-at-yg** [comment]
closing as out of date / stale. When it becomes an active problem again feel free to re-open.

**Comment by strummy96** [comment]
I am having this issue while trying to compile my project with pyinstaller. same error as shown in #15 - but I can see '_base.py' in the geoprocessing folder. any progress made on this? Thanks!

**Comment by mhw-at-yg** [comment]
@strummy96 is your project somewhere public? Feel free to send it to me at matt.wilkie@yukon.ca if it's something that shouldn't be shared. Failing that give more details on the environment so I can try and reproduce the error locally.
