### ISSUE TITLE
No module named numpy

### ISSUE THREAD

**Issue by ishiland** [JamesRamm/archook#12]
Im getting `No module named numpy` when setting up virtual environments. Is there a reason its not in setup.py as a dependency?

**Comment by JamesRamm** [comment]
Yes,
Numpy is not a direct dependency of archook. It's a dependency of arcpy itself.
I'm happy to consider arguments one way or the other as to whether archook should install arcpy dependencies itself.

**Comment by ishiland** [comment]
Sorry, I didn't see the previously closed issue. Its not a big deal for my use case so I will close this and leave the decision to you. Thanks.
