### ISSUE TITLE
Project maintener role

### ISSUE THREAD

**Issue by mhw-at-yg** [JamesRamm/archook#17]
Hi James,

I'm willing to take on the maintainer role for this project. :)

**Comment by logan-pugh** [comment]
@mhw-at-yg if you haven't already you might try emailing the author at jamessramm@gmail.com as well

Thanks for offering to take this on!

**Comment by JamesRamm** [comment]
@mhw-at-yg 
thanks for volunteering! 
I have sent a collaborator invitation to you

**Comment by mhw-at-yg** [comment]
Accepted, thanks. :)

And thanks for a working example illustrating that it's actually quite easy to get an env to talk to ArcPy. My previous attempts made it much too complicated!
