### ISSUE TITLE
pip installs an old version

### ISSUE THREAD

**Issue by vibb** [JamesRamm/archook#31]
I've install the archook via "pip install archook", my python version is 2.7.13 and my ArcMap is 10.5. When I call archook.get_arcpy() and import arcpy, errors show "no arcpy module". So I check the archook in my python install path. I find the installed archook.py is not the same file in github.

**Comment by mhw-at-yg** [comment]
A work around to get the current version is to pip install straight from github using the manual developer mode recipe at the end of the Readme (https://github.com/JamesRamm/archook#installation). 

(Just fixed this morning with 1043e4cdc060e7f6e6ed65a13ea1ac6657b0a838. It was broken before but I didn't know until this error report. So thanks.)

**Comment by franTarkenton** [comment]
You can also install using pip straight out of the git repo:

`pip install git+https://github.com/JamesRamm/archook`

**Comment by mhw-at-yg** [comment]
close by documenting github install in Readme, and saying it's preferred to PyPi
